name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'   # ensure matching in deploy step

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel project config / env
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy prebuilt to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Show deployment URL
        run: echo "=== Deployed to $VERCEL_URL ==="